### ISSUE TITLE
Error while reading index

### ISSUE THREAD

**Issue by weedcentipede** [jason-weirather/AlignQC#14]
Hi, 

While running AlignQC,, I got the following error:
```
Reading reference fasta
Reading index
Traceback (most recent call last):age
  File "/usr/local/bin/alignqc", line 11, in <module>
    sys.exit(entry_point())
  File "/usr/local/lib/python2.7/dist-packages/alignqc/alignqc.py", line 47, in entry_point
    main(args,operable_argv)
  File "/usr/local/lib/python2.7/dist-packages/alignqc/alignqc.py", line 17, in main
    analyze.external_cmd(operable_argv,version=version)
  File "/usr/local/lib/python2.7/dist-packages/alignqc/analyze.py", line 88, in external_cmd
    main(args)
  File "/usr/local/lib/python2.7/dist-packages/alignqc/analyze.py", line 54, in main
    prepare_all_data.external(args)
  File "/usr/local/lib/python2.7/dist-packages/alignqc/prepare_all_data.py", line 844, in external
    main(args)
  File "/usr/local/lib/python2.7/dist-packages/alignqc/prepare_all_data.py", line 65, in main
    make_data_bam_reference(args)
  File "/usr/local/lib/python2.7/dist-packages/alignqc/prepare_all_data.py", line 404, in make_data_bam_reference
    bam_to_context_error_plot.external_cmd(cmd)
  File "/usr/local/lib/python2.7/dist-packages/alignqc/bam_to_context_error_plot.py", line 146, in external_cmd
    main(args)
  File "/usr/local/lib/python2.7/dist-packages/alignqc/bam_to_context_error_plot.py", line 44, in main
    epf.add_alignment(e)
  File "/usr/local/lib/python2.7/dist-packages/seqtools/errors.py", line 74, in add_alignment
    ae = AlignmentErrors(align)
  File "/usr/local/lib/python2.7/dist-packages/seqtools/errors.py", line 698, in __init__
    self._hpas = self._misalign_split(alns) # split alignment into homopolymer groups
  File "/usr/local/lib/python2.7/dist-packages/seqtools/errors.py", line 1105, in _misalign_split
    tchar = x['target'][i]
IndexError: string index out of range.
```
Can you please help me?
Thanks in advance, 
Luis Alfonso.

**Comment by weedcentipede** [comment]
Well, this error is produced when you use .bam that it's not from the reference you're using.
