### ISSUE TITLE
IOError: Not a gzipped file

### ISSUE THREAD

**Issue by SziKayLeung** [jason-weirather/AlignQC#21]
Hello Jason, 

I've been trying to use the alignqc analyze for my mapped pacbio long reads (aligned by GMAP and sorted) with mouse genome reference fa and gtf file. However, keep running into the same issue with IOError: Not a gzipped file. 

Any help will be greatly appreciated. Thank you! 

Best, 
Szi Kay

```
(anaCogent) -bash-4.2$ alignqc analyze /mnt/data1/Szi/C21/GMAP/C21.hq_isoforms.fastq.sorted.bam -g /mnt/data1/Szi/reference/GRCm38.p4.genome.fa -t /mnt/data1/Szi/reference/GRCm38.p4.gtf -o C21.alignqc.xhtml --output_folder /mnt/data1/Szi/C21/align
Using Rscript version:
R scripting front-end version 3.3.2 (2016-10-31)
Traceback (most recent call last):
  File "/home/sLeung/.conda/envs/anaCogent/bin/alignqc", line 11, in <module>
    sys.exit(entry_point())
  File "/home/sLeung/.conda/envs/anaCogent/lib/python2.7/site-packages/alignqc/alignqc.py", line 47, in entry_point
    main(args,operable_argv)
  File "/home/sLeung/.conda/envs/anaCogent/lib/python2.7/site-packages/alignqc/alignqc.py", line 17, in main
    analyze.external_cmd(operable_argv,version=version)
  File "/home/sLeung/.conda/envs/anaCogent/lib/python2.7/site-packages/alignqc/analyze.py", line 88, in external_cmd
    main(args)
  File "/home/sLeung/.conda/envs/anaCogent/lib/python2.7/site-packages/alignqc/analyze.py", line 48, in main
    gobj = GTFFile(ginf)
  File "/home/sLeung/.conda/envs/anaCogent/lib/python2.7/site-packages/seqtools/format/gtf.py", line 19, in __init__
    for line in filehandle:
  File "/home/sLeung/.conda/envs/anaCogent/lib/python2.7/gzip.py", line 464, in readline
    c = self.read(readsize)
  File "/home/sLeung/.conda/envs/anaCogent/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/home/sLeung/.conda/envs/anaCogent/lib/python2.7/gzip.py", line 303, in _read
    self._read_gzip_header()
  File "/home/sLeung/.conda/envs/anaCogent/lib/python2.7/gzip.py", line 197, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file

```

**Comment by Yuyao1025** [comment]
Have you solved this problem yet? I met this problem, too. Could you please share your experience for me?Thanks so much!

**Comment by SziKayLeung** [comment]
No I haven't, but do let me know too if you have solved the problem - Thanks!

**Comment by Yuyao1025** [comment]
I had solved it after i compressed .gft file to .gz format. I think there is a bug exist in "analyze.py", line 46 and line 47. I think you can also solve these problem through fixing this bug.

**Comment by abayega** [comment]
Hi Szi Kay,

I think AlignQC works with gpd file not gtf. This could be a problem too.

**Comment by abayega** [comment]
Sorry, my bad, just realised that gtf is actually preferred.

**Comment by SziKayLeung** [comment]
Thank you @Yuyao1025, I agree it's the bug in line 46 and 47. The bug was fixed by removing the word "gzip" after open on line 47. So the following code works for anyone with the same issue:

if args.gtf[-3:] == '.gz': ginf = gzip.open(args.gtf)
     else: ginf = open(args.gtf)

and thank you @abayega for commenting!
