### ISSUE TITLE
annotation error

### ISSUE THREAD

**Issue by ma-diroma** [jason-weirather/AlignQC#6]
Hi,

I am trying to use your tool using a RefSeq annotation file in gpd format. It includes non-coding RNAs, thus fields cdsStart and cdsEnd are empty (".").
The process exits with an error, so I am wondering if the annotation file should not include non-coding RNAs.
Attached please find the error.
Thanks,
Maria Angela

Finding genomic features and assigning reads membership
/home/sw/AlignQC-1.2/utilities/annotate_from_genomic_features.py --output_beds /home/madiroma/tmp/weirathe.Lt1qCw/data/beds /home/madiroma/tmp/weirathe.Lt1qCw/data/best.sorted.gpd.gz /home/madiroma/useful_annotations/refGene_hg19.gpd /home/madiroma/tmp/weirathe.Lt1qCw/data/chrlens.txt -o /home/madiroma/tmp/weirathe.Lt1qCw/data/read_genomic_features.txt.gz
Reading Exons
Traceback (most recent call last):
  File "/home/sw/AlignQC-1.2/bin/alignqc", line 44, in <module>
    main()
  File "/home/sw/AlignQC-1.2/bin/alignqc", line 24, in main
    analyze.external_cmd(" ".join(operable_argv),version=version)
  File "/home/sw/AlignQC-1.2/utilities/analyze.py", line 77, in external_cmd
    main(args)
  File "/home/sw/AlignQC-1.2/utilities/analyze.py", line 44, in main
    prepare_all_data.external(args)
  File "/home/sw/AlignQC-1.2/utilities/prepare_all_data.py", line 764, in external
    main(args)
  File "/home/sw/AlignQC-1.2/utilities/prepare_all_data.py", line 76, in main
    make_data_bam_annotation(args)
  File "/home/sw/AlignQC-1.2/utilities/prepare_all_data.py", line 423, in make_data_bam_annotation
    annotate_from_genomic_features.external_cmd(cmd)
  File "/home/sw/AlignQC-1.2/utilities/annotate_from_genomic_features.py", line 216, in external_cmd
    main(args)
  File "/home/sw/AlignQC-1.2/utilities/annotate_from_genomic_features.py", line 52, in main
    exonbed += [x.get_range() for x in gpd.exons]
  File "/home/sw/AlignQC-1.2/pylib/Bio/Format/GPD.py", line 48, in exons
    self._initialize()
  File "/home/sw/AlignQC-1.2/pylib/Bio/Format/GPD.py", line 21, in _initialize
    self._entry = _line_to_entry(self._line)
  File "/home/sw/AlignQC-1.2/pylib/Bio/Format/GPD.py", line 79, in _line_to_entry
    d['cdsStart'] = int(f[6])
ValueError: invalid literal for int() with base 10: '.'

**Comment by jason-weirather** [comment]
Hi Maria Angela,

GPD is a loosely defined format, so I recommend checking you are following the version specific to what AlignQC is expecting.

https://www.healthcare.uiowa.edu/labs/au/IDP/IDP_gpd_format.asp

If you're not sure you could post up a snippet from your GPD file and I can see if it fits the format.

Also we have recently pushed out an updated version of AlignQC (major update), now AlignQC can take either GTF or GPD files.

https://github.com/jason-weirather/AlignQC/releases/tag/v2.0.4

You can also install the new alignqc version via pip `pip install AlignQC` from a python 2.7 environment or you can run it through a docker `docker run vacation/alignqc alignqc`.

**Comment by ma-diroma** [comment]
Hi Jason,

I got my gpd file using a script produced by IDP tool authors.
I show you its content, for a coding and a non coding RNA:

refgene_NR_135482	refiso_NR_135482	chrUn_gl000224	+	102502	110268	.	.	3	102502,106077,110187,	102591,106136,110268,
refgene_NM_001242524	refiso_NM_001242524	chr6_qbl_hap6	-	4264796	4281012	4268880	4273798	6	4264796,4268865,4269246,4269868,4273698,4280913,	4265575,4269032,4269528,4270114,4273897,4281012,

Fon non-coding, cds coordinates are obviously empty.
Anyway, I will use the latest version of AlignQC to directly use a gtf file for annotation.
Thanks,
Maria Angela

**Comment by jason-weirather** [comment]
I see.  Yes, I think my GPD parser is expecting integers where you have your periods, i generally just set them to the bounds of the transcript.  But having it accept some null like the period for CDS seems like better behavior. If you have any trouble with the GTF parsing please let me know because it hasn't been tested extensively. 

I'll put it on my todo list to handle periods in the GPD format CDS fields.

Thanks!

**Comment by ma-diroma** [comment]
Hi Jason,

I am testing the latest version (2.0.4) with a gtf file.
This is my command

alignqc analyze -g hg19.fasta -t refGene_hg19.gtf.gz --output_folder /path/to/output_folder --threads 10 --tempdir /path/to/tmp/ sorted.bam

and I got this new error
...
combining results
Now find best entry for each read
sort: unrecognized option '--parallel=10'
Usare `sort --help' per ulteriori informazioni.
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 405, in _handle_results
    cache[job]._set(i, obj)
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 572, in _set
    self._callback(self._value)
  File "/usr/local/lib/python2.7/site-packages/AlignQC-2.0.4-py2.7.egg/alignqc/bam_preprocess.py", line 63, in process_chunk
    g_sortpipe.stdin.write(val+"\n")
IOError: [Errno 32] Broken pipe

however the process is still running (I killed it).
Could you please tell me how to solve?

Thanks,
Maria Angela

**Comment by jason-weirather** [comment]
Sorry for my slow reply.  Yes the issue there is the requirement for Linux's
coreutils must be 8.6 or better. Some older linux systems don't have this.
It uses the parallelized version of `sort`.  I could probably work around
it to make it run on older machines, but i highly recommend that using sort
with the --parallel option to make life better in a lot of circumstances in
bioinformatics.  You could either update your coreutils, or run a conda
environment with updated core utilities or run from the docker to get it
going.

**Comment by ma-diroma** [comment]
Hi,

Thanks. I am updating my linux system. I'll let you know if then it works.

Best wishes,
Maria Angela

**Comment by ma-diroma** [comment]
Hi Jason,

I updated my Linux system and the issue was solved. However, I got other errors related to the annotation step. I have tried using both my gpd file (obtained from UCSC hg19 ref_gene.gtf) and the gtf file. In the first case, I have the same error previousy reported (invalid literal for int() with base 10: '.' referred to cdsStart and cdsEnd of non-coding RNAs). In the second case, I got this error

reading read genepred
stream loci
Traceback (most recent call last):
  File "/usr/local/bin/alignqc", line 9, in <module>
    load_entry_point('AlignQC==2.0.4', 'console_scripts', 'alignqc')()
  File "/usr/local/lib/python2.7/site-packages/AlignQC-2.0.4-py2.7.egg/alignqc/alignqc.py", line 47, in entry_point
    main(args,operable_argv)
  File "/usr/local/lib/python2.7/site-packages/AlignQC-2.0.4-py2.7.egg/alignqc/alignqc.py", line 17, in main
    analyze.external_cmd(operable_argv,version=version)
  File "/usr/local/lib/python2.7/site-packages/AlignQC-2.0.4-py2.7.egg/alignqc/analyze.py", line 88, in external_cmd
    main(args)
  File "/usr/local/lib/python2.7/site-packages/AlignQC-2.0.4-py2.7.egg/alignqc/analyze.py", line 54, in main
    prepare_all_data.external(args)
  File "/usr/local/lib/python2.7/site-packages/AlignQC-2.0.4-py2.7.egg/alignqc/prepare_all_data.py", line 844, in external
    main(args)
  File "/usr/local/lib/python2.7/site-packages/AlignQC-2.0.4-py2.7.egg/alignqc/prepare_all_data.py", line 69, in main
    make_data_bam_annotation(args)
  File "/usr/local/lib/python2.7/site-packages/AlignQC-2.0.4-py2.7.egg/alignqc/prepare_all_data.py", line 725, in make_data_bam_annotation
    annotated_read_bias_analysis.external_cmd(cmd)
  File "/usr/local/lib/python2.7/site-packages/AlignQC-2.0.4-py2.7.egg/alignqc/annotated_read_bias_analysis.py", line 334, in external_cmd
    main(args)
  File "/usr/local/lib/python2.7/site-packages/AlignQC-2.0.4-py2.7.egg/alignqc/annotated_read_bias_analysis.py", line 46, in main
    rvals = do_locus(l0,l1,l2,args)
  File "/usr/local/lib/python2.7/site-packages/AlignQC-2.0.4-py2.7.egg/alignqc/annotated_read_bias_analysis.py", line 130, in do_locus
    rvals.append(do_tx_line([tx_to_ref[tx],tx_to_read[tx].values(),args]))
  File "/usr/local/lib/python2.7/site-packages/AlignQC-2.0.4-py2.7.egg/alignqc/annotated_read_bias_analysis.py", line 190, in do_tx_line
    outrange = reads[-1].get_range()
AttributeError: 'GPD' object has no attribute 'get_range'

I have also tried to use your tool on an alignment onto hg38 and using the refFlat.txt.gz you used in your work. I got another error

Generate the depth bed for the mapped reads
gpd_to_bed_depth.py /home4/madiroma/u937_cDNA/nanopore/gmap_hg38/tmp/weirathe.LsA0AP/data/best.sorted.gpd.gz -o /home4/madiroma/u937_cDNA/nanopore/gmap_hg38/tmp/weirathe.LsA0AP/data/depth.sorted.bed.gz --threads 10
Traceback (most recent call last):
  File "/usr/local/bin/alignqc", line 9, in <module>
    load_entry_point('AlignQC==2.0.4', 'console_scripts', 'alignqc')()
  File "/usr/local/lib/python2.7/site-packages/AlignQC-2.0.4-py2.7.egg/alignqc/alignqc.py", line 47, in entry_point
    main(args,operable_argv)
  File "/usr/local/lib/python2.7/site-packages/AlignQC-2.0.4-py2.7.egg/alignqc/alignqc.py", line 17, in main
    analyze.external_cmd(operable_argv,version=version)
  File "/usr/local/lib/python2.7/site-packages/AlignQC-2.0.4-py2.7.egg/alignqc/analyze.py", line 88, in external_cmd
    main(args)
  File "/usr/local/lib/python2.7/site-packages/AlignQC-2.0.4-py2.7.egg/alignqc/analyze.py", line 54, in main
    prepare_all_data.external(args)
  File "/usr/local/lib/python2.7/site-packages/AlignQC-2.0.4-py2.7.egg/alignqc/prepare_all_data.py", line 844, in external
    main(args)
  File "/usr/local/lib/python2.7/site-packages/AlignQC-2.0.4-py2.7.egg/alignqc/prepare_all_data.py", line 60, in main
    make_data_bam(args)
  File "/usr/local/lib/python2.7/site-packages/AlignQC-2.0.4-py2.7.egg/alignqc/prepare_all_data.py", line 184, in make_data_bam
    gpd_to_bed_depth(cmd)
  File "/usr/local/lib/python2.7/site-packages/seq_tools-1.0.7-py2.7.egg/seqtools/cli/utilities/gpd_to_bed_depth.py", line 60, in external_cmd
    main(args)
  File "/usr/local/lib/python2.7/site-packages/seq_tools-1.0.7-py2.7.egg/seqtools/cli/utilities/gpd_to_bed_depth.py", line 27, in main
    for covs in results:
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 269, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
ValueError: Expected lines to be ordered but they appear not to be ordered on line 525569

Any idea?
Best,
Maria Angela

**Comment by jason-weirather** [comment]
Would you be able to share a link to the annotation file causing the error?  It sounds like the bug where '.' are not processed is still causing your problem and I should just fix that.  It would help to have your gtf file to make sure i'm replicating your error.

**Comment by ma-diroma** [comment]
[refGene_hg19.gtf.gz](https://github.com/jason-weirather/AlignQC/files/1306832/refGene_hg19.gtf.gz)

[refGene_hg19.gpd.gz](https://github.com/jason-weirather/AlignQC/files/1306835/refGene_hg19.gpd.gz)

**Comment by jason-weirather** [comment]
Hi @ma-diroma Sorry I've lost track of this for so long and maybe you've moved on, but I'm trying to help another user with a similar error I'm having trouble replicating which looks similar to yours.  I have replicated your error and found it occurs on `gpd` but not on `gtf` format.  I'm going to update the documentation to recommend using the GTF format, and mention the issue with GPD since GTF is more popular and I don't have a lot of time to work out a fix right now.  Thanks for helping me find this.

**Comment by ma-diroma** [comment]
Hi Jason,

thanks for your warning. However, I got this error also using a GTF file...

Best wishes,
Maria Angela

--
Maria Angela Diroma, PhD

Istituto di Biomembrane, Bioenergetica e Biotecnologie Molecolari - CNR
Via Amendola 165/A
70126 Bari (Italy)

Skype: mariangela.diroma

2017-12-23 16:47 GMT+01:00 Jason L Weirather <notifications@github.com>:
